version: '3'

services:
  nextjs-app:
    build: .
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
    volumes:
      - .:/app
    command: npm run start
    restart: always
